In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url = "https://myanimelist.net/topmanga.php"
page=requests.get(url)

In [4]:
page

In [5]:
page.text

'\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n\n<html lang="en" class="appearance-none">\n<head>\n    \n<link rel="preconnect" href="//www.googletagmanager.com/" crossorigin="anonymous"/>\n<link rel="preconnect" href="https://cdn.myanimelist.net" crossorigin="anonymous"/>\n<title>\n  Top Manga - MyAnimeList.net\n</title>\n<meta name="description" content="Browse the highest-ranked manga on MyAnimeList, the internet&#039;s largest manga database. Find the top manga, novels, one-shots and more!" />\n\n  \n<meta name="keywords" content="anime, myanimelist, anime news, manga" />\n  \n\n        \n          \n          \n  <link rel="next" href="https://myanimelist.net/topmanga.php?limit=50" />\n\n\n\n\n<meta property="og:locale" content="en_US"><meta property="fb:app_id" content="360769957454434"><meta property="og:site_name" content="MyAnimeList.net"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@myanimelist"><meta property="og:title" content=" Top Manga - MyAnimeList.net "><meta property="og:image" content="https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png"><meta name="twitter:image:src" content="https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png"><meta property="og:url" content="https://myanimelist.net/topmanga.php"><meta property="og:description" content="Browse the highest-ranked manga on MyAnimeList, the internet&#039;s largest manga database. Find the top manga, novels, one-shots and more!">\n\n<meta name="referrer" content="default"><link rel="manifest" href="/manifest.json">\n\n<meta name=\'csrf_token\' content=\'c0296ea7ecf02c96cb39dc5fcffbd53048de402a\'>\n<meta name="fo-verify" content="1e927243-8e02-48e3-b098-a7b78c5b4e36"><meta name="viewport" content="initial-scale=1" /><link rel="preload" as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/style-efe7646068.css" />\n<link rel="preload" as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/dark-84ab9757bf.css" />\n<link rel="preload" as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/header-f993536e06.js" />\n<link rel="preload" as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/all-7b7e52f028.js" />\n\n<link rel="stylesheet" type="text/css" href="https://cdn.myanimelist.net/static/assets/css/pc/style-efe7646068.css" />\n<link rel="stylesheet" type="text/css" href="https://cdn.myanimelist.net/static/assets/css/pc/dark-84ab9757bf.css" />\n\n<script type="text/javascript" src="https://cdn.myanimelist.net/static/assets/js/pc/header-f993536e06.js"></script>\n<script type="text/javascript" src="https://cdn.myanimelist.net/static/assets/js/pc/all-7b7e52f028.js" id="alljs" data-params=\'{&quot;origin_url&quot;:&quot;https:\\/\\/myanimelist.net&quot;}\' async="async"></script>\n\n\n\n<link rel="search" type="application/opensearchdescription+xml" href="https://myanimelist.net/plugins/myanimelist.xml" title="MyAnimeList" />\n\n<link rel="shortcut icon" href="https://cdn.myanimelist.net/images/favicon.ico" />\n\n<meta name=\'recaptcha_site_key\' content=\'6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4\'>\n<script>\nwindow.GRECAPTCHA_SITE_KEY = \'6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4\';\n</script>\n<script src=\'https://www.google.com/recaptcha/api.js?render=6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4\' async defer></script>\n    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">\n\n<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1473193330168238" crossorigin="anonymous"></script>\n<script type="text/javascript" src="https://cdn.myanimelist.net/js/quantcast_choice.js?v=1742367258"></script>\n<script type="text/javascript" src="https://cdn.myanimelist.net/js/cmp.js?v=1742367258"></script>\n<script src="https://btloader.com/tag?o=5110059113906176&upapi=true" async></script> <script src="https://hb.vntsm.com/v3/live/ad-manager.min.js" type="text/javascript" data-site-id="65a1835ac178db4aeb9540ce" data-mode="scan" async></script>\n<script>\n  var clientDarkMode = window.matchMedia("(prefers-color-scheme:dark)").matches;\n  let darkMode = false\n\n  if (clientDarkMode) {\n    if (!$(\'html\').hasClass("appearance-light")) { // SystemSetting = Dark && MAL UserSettings != Light\n      darkMode = true\n    }\n  } else if ($(\'html\').hasClass("appearance-dark")) { // MAL UserSettings = Dark\n    darkMode = true\n  }\n\n    if (darkMode) {\n    $(\'html\').addClass("dark-mode");\n  }\n    $(document).ready(function() {\n    if (darkMode) {\n      if($(\'.js-color-pc-constant\').length){$(\'.js-color-pc-constant\').addClass("color-pc-constant");}\n    }\n  });\n</script>\n\n</head>\n\n<body onload=" " class="page-common " data-country-code="IN"  data-time="1742367258" >\n<div id="myanimelist">\n\n    \n  \n    <script type=\'text/javascript\'>\n    window.MAL.SkinAd.prepareForSkin(\'\');\n  </script>\n\n    <div id="ad-skin-bg-left" class="ad-skin-side-outer ad-skin-side-bg bg-left">\n    <div id="ad-skin-left" class="ad-skin-side left" style="display: none;">\n      <div id="ad-skin-left-absolute-block">\n        <div id="ad-skin-left-fixed-block"></div>\n      </div>\n    </div>\n  </div>\n        <div class="wrapper "><div id="headerSmall" class=""><a href="/" class="link-mal-logo">MyAnimeList.net</a>    <script>(deployads = window.deployads || []).disablePageSegmentSessionTracking = true; </script>\n    <script>(deployads = window.deployads || []).pageSegment = \'top_manga\';</script>\n\n\n<script>\n    var trackOutboundLink = function(url) {\n        ga(\'send\', \'event\', \'outbound\', \'click\', url, {\n            \'transport\': \'beacon\',\n            \'hitCallback\': function(){return true;}\n        });\n    }\n</script><div class="banner-header-anime-straming header-mini-banner" style="right:480px;">\n  <a href="https://id.anime.foundation/events/writing-comp-finalist-vote-2025?utm_source=MAL&utm_medium=mb_writingcontest2024&utm_content=publicvote" onclick="trackOutboundLink(\'https://id.anime.foundation/events/writing-comp-finalist-vote-2025?utm_source=MAL&utm_medium=mb_writingcontest2024&utm_content=publicvote\')"> <img src="/c/img/resources/mb/mini_banner_20250225_writing_contest.png" width="250" height="36" alt="WritingContest" title="WritingContest"> </a>\n</div>\n\n\n<div id="header-menu" ><div class="header-menu-login"><a class="btn-mal-service ga-click ga-impression" data-ga-click-type="hide-ads" data-ga-impression-type="hide-ads"\n             href="https://myanimelist.net/membership?_location=mal_h_u" onClick="ga_mal_banner()">Hide Ads</a><a class="btn-login" href="https://myanimelist.net/login.php?from=%2Ftopmanga.php" id="malLogin" onClick="ga_notlogin()">Login</a><a class="btn-signup" href="https://myanimelist.net/register.php?from=%2Ftopmanga.php" onClick="ga_registration()">Sign Up</a></div></div></div>  <div id="menu" class="">\n    <div id="menu_right"><script type="text/x-template" id="incremental-result-item-anime"><div class="list anime" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info anime"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Aired: ${ item.payload.aired }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info anime"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-manga"><div class="list manga" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info manga"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Published: ${ item.payload.published }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info manga"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-character"><div class="list character" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info character"><div class="name"  v-html="item.name"></div><div class="extra-info"><ul class="related-works"><li v-for="work in item.payload.related_works" class="fs-i">- ${ work }</li></ul>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info character"><div class="name"  v-html="item.name"></div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-person"><div class="list person" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info person"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.alternative_name">${ item.payload.alternative_name }<br></span>Birthday: ${ item.payload.birthday }<br>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info person"><div class="name">${ item.name }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-company"><div class="list company" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info company"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.japanese">(${ item.payload.japanese })<br></span>\n                        Anime titles: ${ item.payload.num_animes.toLocaleString() }<br>\n                        Favorites: ${item.payload.favorites.toLocaleString()}\n                    </div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info company"><div class="name">${ item.name }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-store"><div class="list store" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info store"></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info store"></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-club"><div class="list club" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info club"><div class="name">${ item.name }</div><div class="extra-info">Members: ${ item.payload.members }<br>Category: ${ item.payload.category }<br>Created by: ${ item.payload.created_by }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info club"><div class="name">${ item.name }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-user"><div class="list user" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info user"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.authority">${ item.payload.authority }<br></span>Joined: ${ item.payload.joined }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info user"><div class="name">${ item.name }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-news"><div class="list news" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-featured"><div class="list featured" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-forum"><div class="list forum" :class="{\'focus\': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{\'background-image\': \'url(\' + item.image_url + \')\'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}\n                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="extra-info">${ item.payload.date }<br><span>in ${ item.payload.category }</span></div></div></div><div class="off" v-if="!focus"><span class="image" :style="{\'background-image\': \'url(\' + item.thumbnail_url + \')\'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}\n                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script type="text/x-template" id="incremental-result-item-separator"><div class="list separator"><div class="separator"><span v-show="item.name == \'anime\'">Anime</span><span v-show="item.name == \'manga\'">Manga</span><span v-show="item.name == \'character\'">Characters</span><span v-show="item.name == \'person\'">People</span><span v-show="item.name == \'company\'">Companies</span></div></div></script><div id="top-search-bar" class="js-color-pc-constant"><form id="searchBar" method="get" class="searchBar" @submit.prevent="jump()"><div class="form-select-outer fl-l"><select name="type" id="topSearchValue" class="inputtext" v-model="type"><option value="all">All</option><option value="anime">Anime</option><option value="manga">Manga</option><option value="character">Characters</option><option value="person">People</option><option value="company">Companies</option><option value="store">Manga Store</option><option value="news">News</option><option value="featured">Featured Articles</option><option value="forum">Forum</option><option value="club">Clubs</option><option value="user">Users</option></select></div><input v-model="keyword" id="topSearchText" type="search"\n            name="topkeyword" class="inputtext fl-l" placeholder="Search Anime, Manga, and more..."\n            size="30" autocomplete="off"\n            @keydown.up.prevent="moveSelection(-1)" @keydown.down.prevent="moveSelection(1)"\n            @focus="isFocused = true" @blur="isFocused = false"><button id="topSearchButon" class="fl-l" :class="{\'notActive\': (keyword.length < 3)}" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button></form><div id="topSearchResultList" class="incrementalSearchResultList" :style="{display: (showResult ? \'block\' : \'none\')}" @mousedown.prevent=""><div v-for="(item, i) in items" @mouseover="selection=i"><component :is="resolveComponent(item)" :item="item" :focus="selection == i" :url="generateItemPageUrl(item)"></component></div><div class="list list-bottom" :class="{\'focus\': selection == -1}" @mouseover="selection = -1"\n               :style="{display: (showViewAllLink ? \'block\' : \'none\')}"><a :href="resultPageUrl">\n              View all results for <span class="fw-b">${ keyword }</span><i v-show="isRequesting" class="fa-solid fa-spinner fa-spin ml4"></i></a></div></div></div></div><div id="menu_left">\n      <ul id="nav" class="js-color-pc-constant">\n        <li class="small"><a href="#" class="non-link">Anime</a>\n          <ul class="x-wider">\n            <li><a href="https://myanimelist.net/anime.php?_location=mal_h_m">Anime Search</a></li>\n            <li><a href="https://myanimelist.net/topanime.php?_location=mal_h_m">Top Anime</a></li>\n            <li><a href="https://myanimelist.net/anime/season?_location=mal_h_m">Seasonal Anime</a></li>\n                        <li><a href="https://myanimelist.net/watch/episode?_location=mal_h_m_a">Videos</a></li>\n            <li><a href="https://myanimelist.net/reviews.php?t=anime&amp;_location=mal_h_m">Reviews</a></li>\n            <li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=anime&amp;_location=mal_h_m">Recommendations</a></li>\n            <li><a href="https://myanimelist.net/forum?topicid=2138549&amp;_location=mal_h_m">2024 Challenge</a></li><li><a href="https://fal.myanimelist.net/?utm_source=MAL&amp;utm_medium=headermenu&amp;utm_campaign=fal&amp;utm_content=falhome&amp;_location=mal_h_m">Fantasy Anime League</a></li></ul>\n        </li>\n        <li class="small"><a href="#" class="non-link">Manga</a>\n          <ul class="x-wider">\n            <li><a href="https://myanimelist.net/manga.php?_location=mal_h_m">Manga Search</a></li>\n            <li><a href="https://myanimelist.net/topmanga.php?_location=mal_h_m">Top Manga</a></li>\n            <li><a href="https://myanimelist.net/manga/adapted?_location=mal_h_m" class="menu-new">Adapted to Anime</a></li>\n            <li><a href="https://myanimelist.net/store?_location=mal_h_m">Manga Store</a></li>\n            <li><a href="https://myanimelist.net/reviews.php?t=manga&amp;_location=mal_h_m">Reviews</a></li>\n            <li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=manga&amp;_location=mal_h_m">Recommendations</a></li>\n            <li><a href="https://myanimelist.net/forum?topicid=2141704&amp;_location=mal_h_m">2024 Challenge</a></li>\n          </ul>\n        </li>\n        <li><a href="#" class="non-link">Community</a>\n          <ul>\n            <li><a href="https://myanimelist.net/stacks?_location=mal_h_m">Interest Stacks</a></li>\n            <li><a href="https://m

In [9]:
soup=BeautifulSoup(page.text)

In [11]:
soup.find_all("h3",class_="manga_h3")[0].text

'Berserk'

In [13]:
name=[]
for i in soup.find_all("h3",class_="manga_h3"):
    name.append(i.text)

In [15]:
details=[]
for i in soup.find_all("div",class_="information di-ib mt4"):
    details.append(i.text)

In [17]:
rating=[]
for j in [9,8,7,6,5,4,3,2,1,0]:
    for i in soup.find_all("span",class_=f"text on score-label score-{j}"):
        rating.append(i.text)

In [19]:
rank=[]
for j in range(0,5):
    for i in soup.find_all("span",class_=f"lightLink top-anime-rank-text rank{j}"):
        rank.append(i.text)

In [21]:
for i in [50,100,150,200,250,300,350,400,450,500,550,600]:
    url1 = f"https://myanimelist.net/topmanga.php?limit={i}"
    page=requests.get(url1)
    soup=BeautifulSoup(page.text)
    for i in soup.find_all("h3",class_="manga_h3"):
        name.append(i.text)
    for i in soup.find_all("div",class_="information di-ib mt4"):
        details.append(i.text)
    for j in [9,8,7,6,5,4,3,2,1,0]:
        for i in soup.find_all("span",class_=f"text on score-label score-{j}"):
            rating.append(i.text)
    for j in range(0,5):
        for i in soup.find_all("span",class_=f"lightLink top-anime-rank-text rank{j}"):
            rank.append(i.text)

In [45]:
import pandas as pd
df=pd.DataFrame({"rank":rank,
                 'name':name,
                "details":details,
                "rating":rating})
df

,rank,name,details,rating
0,1,Berserk,\n Manga (? vols)\n Aug 1989 - \...,9.47
1,2,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,\n Manga (24 vols)\n Jan 2004 - ...,9.32
2,3,Vagabond,\n Manga (37 vols)\n Sep 1998 - ...,9.26
3,4,One Piece,\n Manga (? vols)\n Jul 1997 - \...,9.22
4,5,Monster,\n Manga (18 vols)\n Dec 1994 - ...,9.16
...,...,...,...,...
645,646,Goukon ni Ittara Onna ga Inakatta Hanashi,\n Manga (? vols)\n Feb 2021 - \...,8.07
646,647,Hitoribocchi no ○○ Seikatsu,\n Manga (8 vols)\n Sep 2013 - A...,8.07
647,648,Nogi Wakaba wa Yuusha de Aru,\n Light Novel (2 vols)\n Jul 20...,8.07
648,649,Orange,\n Light Novel (3 vols)\n Jul 20...,8.07
649,650,Mahou Shoujo Madoka★Magica,\n Manga (3 vols)\n Feb 2011 - M...,8.07

In [25]:
top_5_rated = df[['name', 'rating']].sort_values(by='rating', ascending=False).head(35)
top_5_rated

                                                 name rating
0                                             Berserk   9.47
1     JoJo no Kimyou na Bouken Part 7: Steel Ball Run   9.32
2                                            Vagabond   9.26
3                                           One Piece   9.22
4                                             Monster   9.16
5                                           Slam Dunk   9.08
6                                        Vinland Saga   9.08
7                                 Fullmetal Alchemist   9.04
10                                         Grand Blue   9.03
8                                      Tian Guan Cifu   9.03
9                                       Guimi Zhi Zhu   9.03
11                      Omniscient Reader's Viewpoint   9.02
12                                            Kingdom   9.01
13                                     Oyasumi Punpun   8.99
14                                    Houseki no Kuni   8.97
15                                               Real   8.95
16                                  20th Century Boys   8.94
17                                      Ashita no Joe   8.94
19                    Monogatari Series: First Season   8.91
20                                      Mo Dao Zu Shi   8.91
18                                        Yotsuba to!   8.91
22  Umineko no Naku Koro ni Chiru - Episode 8: Twi...   8.90
21                   Monogatari Series: Second Season   8.90
23  Kaguya-sama wa Kokurasetai: Tensai-tachi no Re...   8.89
24                                Mikkakan no Koufuku   8.87
25                                                GTO   8.87
26                                    3-gatsu no Lion   8.86
27                                          Haikyuu!!   8.86
28                                     Tian Guan Cifu   8.85
29                                     Koe no Katachi   8.85
32                                  Sousou no Frieren   8.83
30                    Monogatari Series: Final Season   8.83
31                                                 86   8.83
33                                   Akatsuki no Yona   8.82
34           Mushoku Tensei: Isekai Ittara Honki Dasu   8.82

In [84]:
df.to_csv(r'C:\Users\dtrri\bot\temp.csv')

In [194]:
len(df)

650

In [47]:
df['details']

0      \n        Manga (? vols)\n        Aug 1989 - \...
1      \n        Manga (24 vols)\n        Jan 2004 - ...
2      \n        Manga (37 vols)\n        Sep 1998 - ...
3      \n        Manga (? vols)\n        Jul 1997 - \...
4      \n        Manga (18 vols)\n        Dec 1994 - ...
                             ...
645    \n        Manga (? vols)\n        Feb 2021 - \...
646    \n        Manga (8 vols)\n        Sep 2013 - A...
647    \n        Light Novel (2 vols)\n        Jul 20...
648    \n        Light Novel (3 vols)\n        Jul 20...
649    \n        Manga (3 vols)\n        Feb 2011 - M...
Name: details, Length: 650, dtype: object

In [51]:
# Function to extract details from the "details" column
def extract_details(detail_text):
    parts = detail_text.strip().split("\n")  # Split by new lines
    format_type = parts[0].strip() if len(parts) > 0 else None
    volume_info = parts[1].strip() if len(parts) > 1 else None
    publication_dates = parts[2].strip() if len(parts) > 2 else None
    
    return pd.Series([format_type, volume_info, publication_dates])

# Apply extraction function to details column
df[['Format', 'Volume Info', 'Publication Dates']] = df['details'].apply(extract_details)

# Drop the original 'details' column
df_cleaned = df.drop(columns=['details'])

# Display cleaned dataset
df_cleaned.head()

,rank,name,rating,Format,Volume Info,Publication Dates
0,1,Berserk,9.47,Manga (? vols),Aug 1989 -,"741,230 members"
1,2,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga (24 vols),Jan 2004 - Apr 2011,"287,722 members"
2,3,Vagabond,9.26,Manga (37 vols),Sep 1998 - May 2015,"417,353 members"
3,4,One Piece,9.22,Manga (? vols),Jul 1997 -,"654,245 members"
4,5,Monster,9.16,Manga (18 vols),Dec 1994 - Dec 2001,"264,699 members"

In [53]:
import re

# Function to extract clean details
def refine_details(detail_text):
    parts = detail_text.strip().split("\n")  # Split by new lines
    
    # Extract format (e.g., "Manga")
    format_type = parts[0].split(" (")[0].strip() if len(parts) > 0 else None
    
    # Extract volume info (e.g., "24 vols")
    volume_info = re.search(r"\((.*?)\)", parts[0])
    volume_count = volume_info.group(1) if volume_info else None
    
    # Extract publication dates
    if len(parts) > 1:
        pub_dates = parts[1].split(" - ")
        start_date = pub_dates[0].strip() if len(pub_dates) > 0 else None
        end_date = pub_dates[1].strip() if len(pub_dates) > 1 else None
    else:
        start_date, end_date = None, None
    
    # Extract member count (from the last part)
    member_count = parts[-1].replace(" members", "").replace(",", "").strip() if len(parts) > 2 else None
    
    return pd.Series([format_type, volume_count, start_date, end_date, member_count])

# Apply extraction function
df_cleaned[['Format', 'Volume Count', 'Start Date', 'End Date', 'Member Count']] = df['details'].apply(refine_details)

# Drop original details column
#df_cleaned = df_cleaned.drop(columns='details',axis=1)

# Display cleaned dataset

df_cleaned.drop(columns=['Volume Info','Publication Dates','rank'],axis=1,inplace=True)

In [ ]:
df_cleaned.insert(0,'Rank',range(1,651))

In [55]:
df_cleaned

,name,rating,Format,Volume Count,Start Date,End Date,Member Count
0,Berserk,9.47,Manga,? vols,Aug 1989,,741230
1,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga,24 vols,Jan 2004,Apr 2011,287722
2,Vagabond,9.26,Manga,37 vols,Sep 1998,May 2015,417353
3,One Piece,9.22,Manga,? vols,Jul 1997,,654245
4,Monster,9.16,Manga,18 vols,Dec 1994,Dec 2001,264699
...,...,...,...,...,...,...,...
645,Goukon ni Ittara Onna ga Inakatta Hanashi,8.07,Manga,? vols,Feb 2021,,5576
646,Hitoribocchi no ○○ Seikatsu,8.07,Manga,8 vols,Sep 2013,Apr 2021,25442
647,Nogi Wakaba wa Yuusha de Aru,8.07,Light Novel,2 vols,Jul 2015,Jan 2017,4899
648,Orange,8.07,Light Novel,3 vols,Jul 2015,Mar 2016,9831
649,Mahou Shoujo Madoka★Magica,8.07,Manga,3 vols,Feb 2011,May 2011,41688

In [57]:
df_cleaned['End Date']=df_cleaned['End Date'].replace('',"unfinished")

In [59]:
df_cleaned['Volume Count']=df_cleaned['Volume Count'].replace('? vols',"unfinished")

In [61]:
df_cleaned

,name,rating,Format,Volume Count,Start Date,End Date,Member Count
0,Berserk,9.47,Manga,unfinished,Aug 1989,unfinished,741230
1,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga,24 vols,Jan 2004,Apr 2011,287722
2,Vagabond,9.26,Manga,37 vols,Sep 1998,May 2015,417353
3,One Piece,9.22,Manga,unfinished,Jul 1997,unfinished,654245
4,Monster,9.16,Manga,18 vols,Dec 1994,Dec 2001,264699
...,...,...,...,...,...,...,...
645,Goukon ni Ittara Onna ga Inakatta Hanashi,8.07,Manga,unfinished,Feb 2021,unfinished,5576
646,Hitoribocchi no ○○ Seikatsu,8.07,Manga,8 vols,Sep 2013,Apr 2021,25442
647,Nogi Wakaba wa Yuusha de Aru,8.07,Light Novel,2 vols,Jul 2015,Jan 2017,4899
648,Orange,8.07,Light Novel,3 vols,Jul 2015,Mar 2016,9831
649,Mahou Shoujo Madoka★Magica,8.07,Manga,3 vols,Feb 2011,May 2011,41688

In [63]:
top_5_rated = df_cleaned[['name', 'rating']].sort_values(by='rating', ascending=False).head(35)
top_5_rated

                                                 name rating
0                                             Berserk   9.47
1     JoJo no Kimyou na Bouken Part 7: Steel Ball Run   9.32
2                                            Vagabond   9.26
3                                           One Piece   9.22
4                                             Monster   9.16
5                                           Slam Dunk   9.08
6                                        Vinland Saga   9.08
7                                 Fullmetal Alchemist   9.04
10                                         Grand Blue   9.03
8                                      Tian Guan Cifu   9.03
9                                       Guimi Zhi Zhu   9.03
11                      Omniscient Reader's Viewpoint   9.02
12                                            Kingdom   9.01
13                                     Oyasumi Punpun   8.99
14                                    Houseki no Kuni   8.97
15                                               Real   8.95
16                                  20th Century Boys   8.94
17                                      Ashita no Joe   8.94
19                    Monogatari Series: First Season   8.91
20                                      Mo Dao Zu Shi   8.91
18                                        Yotsuba to!   8.91
22  Umineko no Naku Koro ni Chiru - Episode 8: Twi...   8.90
21                   Monogatari Series: Second Season   8.90
23  Kaguya-sama wa Kokurasetai: Tensai-tachi no Re...   8.89
24                                Mikkakan no Koufuku   8.87
25                                                GTO   8.87
26                                    3-gatsu no Lion   8.86
27                                          Haikyuu!!   8.86
28                                     Tian Guan Cifu   8.85
29                                     Koe no Katachi   8.85
32                                  Sousou no Frieren   8.83
30                    Monogatari Series: Final Season   8.83
31                                                 86   8.83
33                                   Akatsuki no Yona   8.82
34           Mushoku Tensei: Isekai Ittara Honki Dasu   8.82

In [246]:
df_cleaned.to_csv(r'C:\Users\dtrri\bot\temp2.csv')

In [51]:
for i in soup.find_all("div",class_="hoverinfo left top"):
    print(i.text)

In [15]:
soup.find_all("span",id_="info2",class_="dark_text")

[]

In [53]:
soup.find_all("div",class_="hoverinfo-contaniner")

[]

In [ ]:
<div class="detail">
              <div id="area2">
  <div id="info2" rel="m2" class="hoverinfo left top" style="left: 238.875px; top: 154.6px; display: none;"><div class="hoverinfo-contaniner"><span></span><div>
  <a href=" https://myanimelist.net/manga/2/Berserk" class="hovertitle">
    Berserk
        (1989)  </a>
</div>
<div style="margin-top: 8px; margin-bottom: 10px;">
  Guts, a former mercenary now known as the Black Swordsman, is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fal
      ...
    <a href="https://myanimelist.net/manga/2/Berserk">read more</a>
  </div>

            <span class="dark_text">Genres:</span>
              Action,       Adventure,       Award Winning,       Drama,       Fantasy,       Horror<br>
              <span class="dark_text">Themes:</span>
              Gore,       Military,       Psychological<br>
              <span class="dark_text">Demographic:</span>
              Seinen<br>
  
<span class="dark_text">Status:</span>
Publishing<br>

<span class="dark_text">Volumes:</span>
Unknown<br>

<span class="dark_text">Score:</span>
9.47
<small>(scored by 372,037 users)</small><br>

<span class="dark_text">Ranked:</span>
#1<br>

<span class="dark_text">Popularity:</span>
#1<br>

<span class="dark_text">Members:</span>
741,049<br>
</div></div>
</div>
            <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/2/Berserk" id="#area2" rel="#info2" style="position: relative; display: inline-block;">Berserk</a></h3>
      <div class="information di-ib mt4">
        Manga (? vols)<br>
        Aug 1989 - <br>
        741,047 members
      </div>
    </div>

In [75]:
for i in soup.find_all("span",class_="dark_text"):
    print(i.text)

Synonyms:
Japanese:
English:
Type:
Volumes:
Chapters:
Status:
Published:
Genres:
Themes:
Demographic:
Serialization:
Authors:
Score:
Ranked:
Popularity:
Members:
Favorites:

In [77]:
soup.find_all("div",class_="hoverinfo-contaniner")

[]

In [85]:
soup.find_all("div",class_="detail")

[<div class="detail">
 <div id="area2">
 <div class="hoverinfo" id="info2" rel="m2"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/2/Berserk" id="#area2" rel="#info2">Berserk</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Aug 1989 - <br/>
         741,055 members
       </div>
 </div>,
 <div class="detail">
 <div id="area1706">
 <div class="hoverinfo" id="info1706" rel="m1706"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/1706/JoJo_no_Kimyou_na_Bouken_Part_7__Steel_Ball_Run" id="#area1706" rel="#info1706">JoJo no Kimyou na Bouken Part 7: Steel Ball Run</a></h3>
 <div class="information di-ib mt4">
         Manga (24 vols)<br/>
         Jan 2004 - Apr 2011<br/>
         287,647 members
       </div>
 </div>,
 <div class="detail">
 <div id="area656">
 <div class="hoverinfo" id="info656" rel="m656"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/656/Vagabond" id="#area656" rel="#info656">Vagabond</a></h3>
 <div class="information di-ib mt4">
         Manga (37 vols)<br/>
         Sep 1998 - May 2015<br/>
         417,230 members
       </div>
 </div>,
 <div class="detail">
 <div id="area13">
 <div class="hoverinfo" id="info13" rel="m13"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/13/One_Piece" id="#area13" rel="#info13">One Piece</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Jul 1997 - <br/>
         654,117 members
       </div>
 </div>,
 <div class="detail">
 <div id="area1">
 <div class="hoverinfo" id="info1" rel="m1"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/1/Monster" id="#area1" rel="#info1">Monster</a></h3>
 <div class="information di-ib mt4">
         Manga (18 vols)<br/>
         Dec 1994 - Dec 2001<br/>
         264,634 members
       </div>
 </div>,
 <div class="detail">
 <div id="area51">
 <div class="hoverinfo" id="info51" rel="m51"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/51/Slam_Dunk" id="#area51" rel="#info51">Slam Dunk</a></h3>
 <div class="information di-ib mt4">
         Manga (31 vols)<br/>
         Sep 1990 - Jun 1996<br/>
         183,677 members
       </div>
 </div>,
 <div class="detail">
 <div id="area642">
 <div class="hoverinfo" id="info642" rel="m642"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/642/Vinland_Saga" id="#area642" rel="#info642">Vinland Saga</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Apr 2005 - <br/>
         327,488 members
       </div><div class="bookstore-information ga-impression" data-ga-impression-param="2|a203e8a5-12a4-4db8-bebf-30046e33c421" data-ga-impression-type="bs_mangaR-desktop-rank"><a class="link ga-click" data-ga-click-param="2|a203e8a5-12a4-4db8-bebf-30046e33c421" data-ga-click-type="bs_mangaR-desktop-rank" href="https://mangamirai.com/product_collections/d9746274-5940-4c91-b4ac-bafe43daa60b/products/a203e8a5-12a4-4db8-bebf-30046e33c421?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><i aria-hidden="true" class="fa-solid fa-cart-shopping mr4"></i><span class="bookstore-name">MANGA MIRAI</span><span class="bookstore-volume">Volume 1</span><span class="bookstore-price has-sale-price"></span><span class="bookstore-price sale-price">$17.99</span></a><a class="bookstore-preview-link bookstore-preview-link-2 ga-click" data-bookstore-id="2" data-ga-click-param="2|a203e8a5-12a4-4db8-bebf-30046e33c421" data-ga-click-type="bs_mangaR-desktop-rank" data-is-sale="1" data-item-collection-id="d9746274-5940-4c91-b4ac-bafe43daa60b" data-item-id="a203e8a5-12a4-4db8-bebf-30046e33c421" data-manga-id="642" href="https://mangamirai.com/users/product_contents/73005eb3-f096-400a-b508-9eb023d0dfdf/book_reader?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><img alt="MANGA MIRAI" class="bookstore-icon light mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_wb.png" title="MANGA MIRAI"/><img alt="MANGA MIRAI" class="bookstore-icon dark mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_bb.png" title="MANGA MIRAI"/>Read Sample
     </a></div>
 </div>,
 <div class="detail">
 <div id="area25">
 <div class="hoverinfo" id="info25" rel="m25"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/25/Fullmetal_Alchemist" id="#area25" rel="#info25">Fullmetal Alchemist</a></h3>
 <div class="information di-ib mt4">
         Manga (27 vols)<br/>
         Jul 2001 - Sep 2010<br/>
         305,677 members
       </div>
 </div>,
 <div class="detail">
 <div id="area130826">
 <div class="hoverinfo" id="info130826" rel="m130826"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/130826/Tian_Guan_Cifu" id="#area130826" rel="#info130826">Tian Guan Cifu</a></h3>
 <div class="information di-ib mt4">
         Novel (6 vols)<br/>
         Feb 2021 - Mar 2022<br/>
         14,615 members
       </div>
 </div>,
 <div class="detail">
 <div id="area162032">
 <div class="hoverinfo" id="info162032" rel="m162032"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/162032/Guimi_Zhi_Zhu" id="#area162032" rel="#info162032">Guimi Zhi Zhu</a></h3>
 <div class="information di-ib mt4">
         Novel (18 vols)<br/>
         May 2020 - Aug 2023<br/>
         8,048 members
       </div>
 </div>,
 <div class="detail">
 <div id="area70345">
 <div class="hoverinfo" id="info70345" rel="m70345"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/70345/Grand_Blue" id="#area70345" rel="#info70345">Grand Blue</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Apr 2014 - <br/>
         185,725 members
       </div>
 </div>,
 <div class="detail">
 <div id="area143441">
 <div class="hoverinfo" id="info143441" rel="m143441"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/143441/Omniscient_Readers_Viewpoint" id="#area143441" rel="#info143441">Omniscient Reader's Viewpoint</a></h3>
 <div class="information di-ib mt4">
         Novel (20 vols)<br/>
         Jan 2022 - Sep 2023<br/>
         20,706 members
       </div>
 </div>,
 <div class="detail">
 <div id="area16765">
 <div class="hoverinfo" id="info16765" rel="m16765"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/16765/Kingdom" id="#area16765" rel="#info16765">Kingdom</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Jan 2006 - <br/>
         183,363 members
       </div>
 </div>,
 <div class="detail">
 <div id="area4632">
 <div class="hoverinfo" id="info4632" rel="m4632"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/4632/Oyasumi_Punpun" id="#area4632" rel="#info4632">Oyasumi Punpun</a></h3>
 <div class="information di-ib mt4">
         Manga (13 vols)<br/>
         Mar 2007 - Nov 2013<br/>
         478,771 members
       </div>
 </div>,
 <div class="detail">
 <div id="area44489">
 <div class="hoverinfo" id="info44489" rel="m44489"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/44489/Houseki_no_Kuni" id="#area44489" rel="#info44489">Houseki no Kuni</a></h3>
 <div class="information di-ib mt4">
         Manga (13 vols)<br/>
         Oct 2012 - Apr 2024<br/>
         149,384 members
       </div><div class="bookstore-information ga-impression" data-ga-impression-param="2|c928d590-9adf-44d6-81b9-eba00a490540" data-ga-impression-type="bs_mangaR-desktop-rank"><a class="link ga-click" data-ga-click-param="2|c928d590-9adf-44d6-81b9-eba00a490540" data-ga-click-type="bs_mangaR-desktop-rank" href="https://mangamirai.com/product_collections/8ceb656e-3128-49fe-80f8-ce65c0ab4f5f/products/c928d590-9adf-44d6-81b9-eba00a490540?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><i aria-hidden="true" class="fa-solid fa-cart-shopping mr4"></i><span class="bookstore-name">MANGA MIRAI</span><span class="bookstore-volume">Volume 1</span><span class="bookstore-price has-sale-price"></span><span class="bookstore-price sale-price">$10.99</span></a><a class="bookstore-preview-link bookstore-preview-link-2 ga-click" data-bookstore-id="2" data-ga-click-param="2|c928d590-9adf-44d6-81b9-eba00a490540" data-ga-click-type="bs_mangaR-desktop-rank" data-is-sale="1" data-item-collection-id="8ceb656e-3128-49fe-80f8-ce65c0ab4f5f" data-item-id="c928d590-9adf-44d6-81b9-eba00a490540" data-manga-id="44489" href="https://mangamirai.com/users/product_contents/87c56906-406a-4df5-99d5-9646f1772a51/book_reader?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><img alt="MANGA MIRAI" class="bookstore-icon light mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_wb.png" title="MANGA MIRAI"/><img alt="MANGA MIRAI" class="bookstore-icon dark mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_bb.png" title="MANGA MIRAI"/>Read Sample
     </a></div>
 </div>,
 <div class="detail">
 <div id="area657">
 <div class="hoverinfo" id="info657" rel="m657"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/657/Real" id="#area657" rel="#info657">Real</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Oct 1999 - <br/>
         97,306 members
       </div>
 </div>,
 <div class="detail">
 <div id="area3">
 <div class="hoverinfo" id="info3" rel="m3"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/3/20th_Century_Boys" id="#area3" rel="#info3">20th Century Boys</a></h3>
 <div class="information di-ib mt4">
         Manga (22 vols)<br/>
         Sep 1999 - Apr 2006<br/>
         283,503 members
       </div>
 </div>,
 <div class="detail">
 <div id="area1303">
 <div class="hoverinfo" id="info1303" rel="m1303"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/1303/Ashita_no_Joe" id="#area1303" rel="#info1303">Ashita no Joe</a></h3>
 <div class="information di-ib mt4">
         Manga (20 vols)<br/>
         Jan 1968 - May 1973<br/>
         57,026 members
       </div><div class="bookstore-information ga-impression" data-ga-impression-param="2|05f1a05e-f797-43c0-a494-bcbe5d7671b5" data-ga-impression-type="bs_mangaR-desktop-rank"><a class="link ga-click" data-ga-click-param="2|05f1a05e-f797-43c0-a494-bcbe5d7671b5" data-ga-click-type="bs_mangaR-desktop-rank" href="https://mangamirai.com/product_collections/2b7eb815-c931-4c16-b84d-39ba711f3126/products/05f1a05e-f797-43c0-a494-bcbe5d7671b5?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><i aria-hidden="true" class="fa-solid fa-cart-shopping mr4"></i><span class="bookstore-name">MANGA MIRAI</span><span class="bookstore-volume">Volume 1</span><span class="bookstore-price has-sale-price"></span><span class="bookstore-price sale-price">$19.99</span></a><a class="bookstore-preview-link bookstore-preview-link-2 ga-click" data-bookstore-id="2" data-ga-click-param="2|05f1a05e-f797-43c0-a494-bcbe5d7671b5" data-ga-click-type="bs_mangaR-desktop-rank" data-is-sale="1" data-item-collection-id="2b7eb815-c931-4c16-b84d-39ba711f3126" data-item-id="05f1a05e-f797-43c0-a494-bcbe5d7671b5" data-manga-id="1303" href="https://mangamirai.com/users/product_contents/3634c76e-8d99-4e82-90c4-2aed4687b4c4/book_reader?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><img alt="MANGA MIRAI" class="bookstore-icon light mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_wb.png" title="MANGA MIRAI"/><img alt="MANGA MIRAI" class="bookstore-icon dark mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_bb.png" title="MANGA MIRAI"/>Read Sample
     </a></div>
 </div>,
 <div class="detail">
 <div id="area104">
 <div class="hoverinfo" id="info104" rel="m104"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/104/Yotsuba_to" id="#area104" rel="#info104">Yotsuba to!</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Mar 2003 - <br/>
         164,992 members
       </div>
 </div>,
 <div class="detail">
 <div id="area14893">
 <div class="hoverinfo" id="info14893" rel="m14893"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/14893/Monogatari_Series__First_Season" id="#area14893" rel="#info14893">Monogatari Series: First Season</a></h3>
 <div class="information di-ib mt4">
         Light Novel (6 vols)<br/>
         Nov 2006 - Jul 2010<br/>
         61,501 members
       </div>
 </div>,
 <div class="detail">
 <div id="area121405">
 <div class="hoverinfo" id="info121405" rel="m121405"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/121405/Mo_Dao_Zu_Shi" id="#area121405" rel="#info121405">Mo Dao Zu Shi</a></h3>
 <div class="information di-ib mt4">
         Novel (4 vols)<br/>
         Dec 2016 - Dec 2016<br/>
         9,244 members
       </div>
 </div>,
 <div class="detail">
 <div id="area23751">
 <div class="hoverinfo" id="info23751" rel="m23751"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/23751/Monogatari_Series__Second_Season" id="#area23751" rel="#info23751">Monogatari Series: Second Season</a></h3>
 <div class="information di-ib mt4">
         Light Novel (6 vols)<br/>
         Oct 2010 - Dec 2011<br/>
         24,241 members
       </div>
 </div>,
 <div class="detail">
 <div id="area34053">
 <div class="hoverinfo" id="info34053" rel="m34053"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/34053/Umineko_no_Naku_Koro_ni_Chiru_-_Episode_8__Twilight_of_the_Golden_Witch" id="#area34053" rel="#info34053">Umineko no Naku Koro ni Chiru - Episode 8: Twilight of the Golden Witch</a></h3>
 <div class="information di-ib mt4">
         Manga (9 vols)<br/>
         Jan 2012 - Jun 2015<br/>
         19,038 members
       </div>
 </div>,
 <div class="detail">
 <div id="area90125">
 <div class="hoverinfo" id="info90125" rel="m90125"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/90125/Kaguya-sama_wa_Kokurasetai__Tensai-tachi_no_Renai_Zunousen" id="#area90125" rel="#info90125">Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen</a></h3>
 <div class="information di-ib mt4">
         Manga (28 vols)<br/>
         May 2015 - Nov 2022<br/>
         284,200 members
       </div>
 </div>,
 <div class="detail">
 <div id="area126479">
 <div class="hoverinfo" id="info126479" rel="m126479"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/126479/Mikkakan_no_Koufuku" id="#area126479" rel="#info126479">Mikkakan no Koufuku</a></h3>
 <div class="information di-ib mt4">
         Novel (1 vols)<br/>
         Dec 2013 - Dec 2013<br/>
         34,636 members
       </div>
 </div>,
 <div class="detail">
 <div id="area336">
 <div class="hoverinfo" id="info336" rel="m336"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/336/GTO" id="#area336" rel="#info336">GTO</a></h3>
 <div class="information di-ib mt4">
         Manga (25 vols)<br/>
         Dec 1996 - Jan 2002<br/>
         178,135 members
       </div><div class="bookstore-information ga-impression" data-ga-impression-param="2|0d238d9f-ab7f-43c9-9181-d1892f2b5d2d" data-ga-impression-type="bs_mangaR-desktop-rank"><a class="link ga-click" data-ga-click-param="2|0d238d9f-ab7f-43c9-9181-d1892f2b5d2d" data-ga-click-type="bs_mangaR-desktop-rank" href="https://mangamirai.com/product_collections/d721b586-eab6-4064-ba85-10184b45fa8c/products/0d238d9f-ab7f-43c9-9181-d1892f2b5d2d?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><i aria-hidden="true" class="fa-solid fa-cart-shopping mr4"></i><span class="bookstore-name">MANGA MIRAI</span><span class="bookstore-volume">Volume 1</span><span class="bookstore-price has-sale-price"></span><span class="bookstore-price sale-price">$10.99</span></a><a class="bookstore-preview-link bookstore-preview-link-2 ga-click" data-bookstore-id="2" data-ga-click-param="2|0d238d9f-ab7f-43c9-9181-d1892f2b5d2d" data-ga-click-type="bs_mangaR-desktop-rank" data-is-sale="1" data-item-collection-id="d721b586-eab6-4064-ba85-10184b45fa8c" data-item-id="0d238d9f-ab7f-43c9-9181-d1892f2b5d2d" data-manga-id="336" href="https://mangamirai.com/users/product_contents/4226faeb-73a8-4d8c-948d-73c4ff71143b/book_reader?utm_source=mal&amp;utm_medium=mangaR-desktop-rank" target="_blank"><img alt="MANGA MIRAI" class="bookstore-icon light mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_wb.png" title="MANGA MIRAI"/><img alt="MANGA MIRAI" class="bookstore-icon dark mr4" src="https://cdn.myanimelist.net/aimage/BookStores/mirai_icon_bb.png" title="MANGA MIRAI"/>Read Sample
     </a></div>
 </div>,
 <div class="detail">
 <div id="area1224">
 <div class="hoverinfo" id="info1224" rel="m1224"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/1224/3-gatsu_no_Lion" id="#area1224" rel="#info1224">3-gatsu no Lion</a></h3>
 <div class="information di-ib mt4">
         Manga (? vols)<br/>
         Jul 2007 - <br/>
         71,975 members
       </div>
 </div>,
 <div class="detail">
 <div id="area35243">
 <div class="hoverinfo" id="info35243" rel="m35243"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/35243/Haikyuu" id="#area35243" rel="#info35243">Haikyuu!!</a></h3>
 <div class="information di-ib mt4">
         Manga (45 vols)<br/>
         Feb 2012 - Jul 2020<br/>
         228,924 members
       </div>
 </div>,
 <div class="detail">
 <div id="area140765">
 <div class="hoverinfo" id="info140765" rel="m140765"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/140765/Tian_Guan_Cifu" id="#area140765" rel="#info140765">Tian Guan Cifu</a></h3>
 <div class="information di-ib mt4">
         Manhua (? vols)<br/>
         Oct 2019 - <br/>
         14,437 members
       </div>
 </div>,
 <div class="detail">
 <div id="area56805">
 <div class="hoverinfo" id="info56805" rel="m56805"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/56805/Koe_no_Katachi" id="#area56805" rel="#info56805">Koe no Katachi</a></h3>
 <div class="information di-ib mt4">
         Manga (7 vols)<br/>
         Aug 2013 - Nov 2014<br/>
         278,600 members
       </div>
 </div>,
 <div class="detail">
 <div id="area44227">
 <div class="hoverinfo" id="info44227" rel="m44227"></div>
 </div>
 <h3 class="manga_h3"><a class="hoverinfo_trigger fs14 fw-b" href="https://myanimelist.net/manga/44227/Monogatari_Series__Final_Season" id="#area44227" rel="#info44227">Monogatari Series: Final Season</a></h3>
 <div class="information di-ib mt4">
         Light Novel (6 vols)<br/>
         Sep 2012 - Sep 2014<br/>
         19,804 members
       </div>
 </div>,
 <div class="detail">
 <div id="area104039">

In [192]:
list_=[]
for i in soup.find_all("div",class_="hoverinfo"):
    list_.append(i)

In [43]:
list_=list(list_)

In [198]:
list_

[<div class="hoverinfo" id="info2" rel="m2"></div>,
 <div class="hoverinfo" id="info1706" rel="m1706"></div>,
 <div class="hoverinfo" id="info656" rel="m656"></div>,
 <div class="hoverinfo" id="info13" rel="m13"></div>,
 <div class="hoverinfo" id="info1" rel="m1"></div>,
 <div class="hoverinfo" id="info51" rel="m51"></div>,
 <div class="hoverinfo" id="info642" rel="m642"></div>,
 <div class="hoverinfo" id="info25" rel="m25"></div>,
 <div class="hoverinfo" id="info130826" rel="m130826"></div>,
 <div class="hoverinfo" id="info162032" rel="m162032"></div>,
 <div class="hoverinfo" id="info70345" rel="m70345"></div>,
 <div class="hoverinfo" id="info143441" rel="m143441"></div>,
 <div class="hoverinfo" id="info16765" rel="m16765"></div>,
 <div class="hoverinfo" id="info4632" rel="m4632"></div>,
 <div class="hoverinfo" id="info44489" rel="m44489"></div>,
 <div class="hoverinfo" id="info657" rel="m657"></div>,
 <div class="hoverinfo" id="info3" rel="m3"></div>,
 <div class="hoverinfo" id="info1303" rel="m1303"></div>,
 <div class="hoverinfo" id="info104" rel="m104"></div>,
 <div class="hoverinfo" id="info14893" rel="m14893"></div>,
 <div class="hoverinfo" id="info121405" rel="m121405"></div>,
 <div class="hoverinfo" id="info23751" rel="m23751"></div>,
 <div class="hoverinfo" id="info34053" rel="m34053"></div>,
 <div class="hoverinfo" id="info90125" rel="m90125"></div>,
 <div class="hoverinfo" id="info126479" rel="m126479"></div>,
 <div class="hoverinfo" id="info336" rel="m336"></div>,
 <div class="hoverinfo" id="info1224" rel="m1224"></div>,
 <div class="hoverinfo" id="info35243" rel="m35243"></div>,
 <div class="hoverinfo" id="info140765" rel="m140765"></div>,
 <div class="hoverinfo" id="info56805" rel="m56805"></div>,
 <div class="hoverinfo" id="info44227" rel="m44227"></div>,
 <div class="hoverinfo" id="info104039" rel="m104039"></div>,
 <div class="hoverinfo" id="info126287" rel="m126287"></div>,
 <div class="hoverinfo" id="info21525" rel="m21525"></div>,
 <div class="hoverinfo" id="info70261" rel="m70261"></div>,
 <div class="hoverinfo" id="info9115" rel="m9115"></div>,
 <div class="hoverinfo" id="info28" rel="m28"></div>,
 <div class="hoverinfo" id="info651" rel="m651"></div>,
 <div class="hoverinfo" id="info7375" rel="m7375"></div>,
 <div class="hoverinfo" id="info74697" rel="m74697"></div>,
 <div class="hoverinfo" id="info144267" rel="m144267"></div>,
 <div class="hoverinfo" id="info147272" rel="m147272"></div>,
 <div class="hoverinfo" id="info89357" rel="m89357"></div>,
 <div class="hoverinfo" id="info123992" rel="m123992"></div>,
 <div class="hoverinfo" id="info86119" rel="m86119"></div>,
 <div class="hoverinfo" id="info100448" rel="m100448"></div>,
 <div class="hoverinfo" id="info85781" rel="m85781"></div>,
 <div class="hoverinfo" id="info86769" rel="m86769"></div>,
 <div class="hoverinfo" id="info26" rel="m26"></div>,
 <div class="hoverinfo" id="info14483" rel="m14483"></div>,
 <div class="hoverinfo" id="info7" rel="m7"></div>,
 <div class="hoverinfo" id="info102875" rel="m102875"></div>,
 <div class="hoverinfo" id="info40171" rel="m40171"></div>,
 <div class="hoverinfo" id="info91941" rel="m91941"></div>,
 <div class="hoverinfo" id="info132678" rel="m132678"></div>,
 <div class="hoverinfo" id="info44347" rel="m44347"></div>,
 <div class="hoverinfo" id="info72467" rel="m72467"></div>,
 <div class="hoverinfo" id="info147769" rel="m147769"></div>,
 <div class="hoverinfo" id="info45143" rel="m45143"></div>,
 <div class="hoverinfo" id="info116778" rel="m116778"></div>,
 <div class="hoverinfo" id="info125036" rel="m125036"></div>,
 <div class="hoverinfo" id="info418" rel="m418"></div>,
 <div class="hoverinfo" id="info21" rel="m21"></div>,
 <div class="hoverinfo" id="info145" rel="m145"></div>,
 <div class="hoverinfo" id="info55215" rel="m55215"></div>,
 <div class="hoverinfo" id="info1133" rel="m1133"></div>,
 <div class="hoverinfo" id="info1859" rel="m1859"></div>,
 <div class="hoverinfo" id="info664" rel="m664"></div>,
 <div class="hoverinfo" id="info121496" rel="m121496"></div>,
 <div class="hoverinfo" id="info100035" rel="m100035"></div>,
 <div class="hoverinfo" id="info4" rel="m4"></div>,
 <div class="hoverinfo" id="info9726" rel="m9726"></div>,
 <div class="hoverinfo" id="info117077" rel="m117077"></div>,
 <div class="hoverinfo" id="info123006" rel="m123006"></div>,
 <div class="hoverinfo" id="info129621" rel="m129621"></div>,
 <div class="hoverinfo" id="info88660" rel="m88660"></div>,
 <div class="hoverinfo" id="info98930" rel="m98930"></div>,
 <div class="hoverinfo" id="info107562" rel="m107562"></div>,
 <div class="hoverinfo" id="info145863" rel="m145863"></div>,
 <div class="hoverinfo" id="info23900" rel="m23900"></div>,
 <div class="hoverinfo" id="info26027" rel="m26027"></div>,
 <div class="hoverinfo" id="info24875" rel="m24875"></div>,
 <div class="hoverinfo" id="info78523" rel="m78523"></div>,
 <div class="hoverinfo" id="info85968" rel="m85968"></div>,
 <div class="hoverinfo" id="info103237" rel="m103237"></div>,
 <div class="hoverinfo" id="info128365" rel="m128365"></div>,
 <div class="hoverinfo" id="info137200" rel="m137200"></div>,
 <div class="hoverinfo" id="info44" rel="m44"></div>,
 <div class="hoverinfo" id="info904" rel="m904"></div>,
 <div class="hoverinfo" id="info6978" rel="m6978"></div>,
 <div class="hoverinfo" id="info81" rel="m81"></div>,
 <div class="hoverinfo" id="info745" rel="m745"></div>,
 <div class="hoverinfo" id="info81669" rel="m81669"></div>,
 <div class="hoverinfo" id="info60783" rel="m60783"></div>,
 <div class="hoverinfo" id="info70399" rel="m70399"></div>,
 <div class="hoverinfo" id="info35513" rel="m35513"></div>,
 <div class="hoverinfo" id="info132214" rel="m132214"></div>,
 <div class="hoverinfo" id="info102256" rel="m102256"></div>,
 <div class="hoverinfo" id="info107931" rel="m107931"></div>,
 <div class="hoverinfo" id="info60553" rel="m60553"></div>,
 <div class="hoverinfo" id="info756" rel="m756"></div>,
 <div class="hoverinfo" id="info9982" rel="m9982"></div>,
 <div class="hoverinfo" id="info118289" rel="m118289"></div>,
 <div class="hoverinfo" id="info114043" rel="m114043"></div>,
 <div class="hoverinfo" id="info116312" rel="m116312"></div>,
 <div class="hoverinfo" id="info145539" rel="m145539"></div>,
 <div class="hoverinfo" id="info37707" rel="m37707"></div>,
 <div class="hoverinfo" id="info61579" rel="m61579"></div>,
 <div class="hoverinfo" id="info399" rel="m399"></div>,
 <div class="hoverinfo" id="info698" rel="m698"></div>,
 <div class="hoverinfo" id="info3006" rel="m3006"></div>,
 <div class="hoverinfo" id="info13245" rel="m13245"></div>,
 <div class="hoverinfo" id="info3031" rel="m3031"></div>,
 <div class="hoverinfo" id="info11514" rel="m11514"></div>,
 <div class="hoverinfo" id="info92559" rel="m92559"></div>,
 <div class="hoverinfo" id="info87844" rel="m87844"></div>,
 <div class="hoverinfo" id="info147448" rel="m147448"></div>,
 <div class="hoverinfo" id="info138533" rel="m138533"></div>,
 <div class="hoverinfo" id="info610" rel="m610"></div>,
 <div class="hoverinfo" id="info1325" rel="m1325"></div>,
 <div class="hoverinfo" id="info2062" rel="m2062"></div>,
 <div class="hoverinfo" id="info11054" rel="m11054"></div>,
 <div class="hoverinfo" id="info134744" rel="m134744"></div>,
 <div class="hoverinfo" id="info23390" rel="m23390"></div>,
 <div class="hoverinfo" id="info66517" rel="m66517"></div>,
 <div class="hoverinfo" id="info105084" rel="m105084"></div>,
 <div class="hoverinfo" id="info164926" rel="m164926"></div>,
 <div class="hoverinfo" id="info22" rel="m22"></div>,
 <div class="hoverinfo" id="info8157" rel="m8157"></div>,
 <div class="hoverinfo" id="info11327" rel="m11327"></div>,
 <div class="hoverinfo" id="info102" rel="m102"></div>,
 <div class="hoverinfo" id="info3083" rel="m3083"></div>,
 <div class="hoverinfo" id="info5744" rel="m5744"></div>,
 <div class="hoverinfo" id="info147171" rel="m147171"></div>,
 <div class="hoverinfo" id="info159387" rel="m159387"></div>,
 <div class="hoverinfo" id="info137303" rel="m137303"></div>,
 <div class="hoverinfo" id="info101396" rel="m101396"></div>,
 <div class="hoverinfo" id="info108177" rel="m108177"></div>,
 <div class="hoverinfo" id="info79993" rel="m79993"></div>,
 <div class="hoverinfo" id="info33327" rel="m33327"></div>,
 <div class="hoverinfo" id="info39859" rel="m39859"></div>,
 <div class="hoverinfo" id="info81211" rel="m81211"></div>,
 <div class="hoverinfo" id="info214" rel="m214"></div>,
 <div class="hoverinfo" id="info1342" rel="m1342"></div>,
 <div class="hoverinfo" id="info21498" rel="m21498"></div>,
 <div class="hoverinfo" id="info44307" rel="m44307"></div>,
 <div class="hoverinfo" id="info79085" rel="m79085"></div>,
 <div class="hoverinfo" id="info146878" rel="m146878"></div>,
 <div class="hoverinfo" id="info30" rel="m30"></div>,
 <div class="hoverinfo" id="info3649" rel="m3649"></div>,
 <div class="hoverinfo" id="info11734" rel="m11734"></div>,
 <div class="hoverinfo" id="info93097" rel="m93097"></div>,
 <div class="hoverinfo" id="info92299" rel="m92299"></div>,
 <div class="hoverinfo" id="info104538" rel="m104538"></div>,
 <div class="hoverinfo" id="info56529" rel="m56529"></div>,
 <div class="hoverinfo" id="info85719" rel="m85719"></div>,
 <div class="hoverinfo" id="info113010" rel="m113010"></div>,
 <div class="hoverinfo" id="info115506" rel="m115506"></div>,
 <div class="hoverinfo" id="info119161" rel="m119161"></div>,
 <div class="hoverinfo" id="info121504" rel="m121504"></div>,
 <div class="hoverinfo" id="info28393" rel="m28393"></div>,
 <div class="hoverinfo" id="info141120" rel="m141120"></div>,
 <div class="hoverinfo" id="info111213" rel="m111213"></div>,
 <div class="hoverinfo" id="info114745" rel="m114745"></div>,
 <div class="hoverinfo" id="info87610" rel="m87610"></div>,
 <div class="hoverinfo" id="info38071" rel="m38071"></div>,
 <div class="hoverinfo" id="info25515" rel="m25515"></div>,
 <div class="hoverinfo" id="info46282" rel="m46282"></div>,
 <div class="hoverinfo" id="info117851" rel="m117851"></div>,
 <div class="hoverinfo" id="info119072" rel="m119072"></div>,
 <div class="hoverinfo" id="info121269" rel="m121269"></div>,
 <div class="hoverinfo" id="info123649" rel="m123649"></div>,
 <div class="hoverinfo" id="info93753" rel="m93753"></div>,
 <div class="hoverinfo" id="info88639" rel="m88639"></div>,
 <div class="hoverinfo" id="info1183" rel="m1183"></div>,
 <div class="hoverinfo" id="info43" rel="m43"></div>,
 <div class="hoverinfo" id="info7519" rel="m7519"></div>,
 <div class="hoverinfo" id="info112988" rel="m112988"></div>,
 <div class="hoverinfo" id="info135496" rel="m135496"></div>,
 <div class="hoverinfo" id="info36413" rel="m36413"></div>,
 <div class="hoverinfo" id="info97244" rel="m97244"></div>,
 <div class="hoverinfo" id="info100323" rel="m100323"></div>,
 <div class="hoverinfo" id="info115922" rel="m115922"></div>,
 <div class="hoverinfo" id="info3299" rel="m3299"></div>,
 <div class="hoverinfo" id="info4658" rel="m4658"></div>,
 <div class="hoverinfo" id="info7482" rel="m7482"></div>,
 <div class="hoverinfo" id="info143325" rel="m143325"></div>,
 <div class="hoverinfo" id="info42001" rel="m42001"></div>,
 <div class="hoverinfo" id="info21499" rel="m21499"></div>,
 <div class="hoverinfo" id="info42" rel="m42"></div>,
 <div class="hoverinfo" id="info1032" rel="m1032"></div>,
 <div class="hoverinfo" id="info1469" rel="m1469"></div>,
 <div class="hoverinfo" id="info3285" rel="m3285"></div>,
 <div class="hoverinfo" id="info6812" rel="m6812"></div>,
 <div class="hoverinfo" id="info112370" rel="m112370"></div>,
 <div class="hoverinfo" id="info119279" rel="m119279"></div>,
 <div class="hoverinfo" id="info124374" rel="m124374"></div>,
 <div class="hoverinfo" id="info155861" rel="m155861"></div>,
 <div class="hoverinfo" id="info743" rel="m743"></div>,
 <div class="hoverinfo" id="info3807" rel="m3807"></div>,
 <div class="hoverinfo" id="info17051" rel="m17051"></div>,
 <div class="hoverinfo" id="info29211" rel="m29211"></div>,
 <div class="hoverinfo" id="info119184" rel="m119184"></div>,
 <div class="hoverinfo" id="info133641" rel="m133641"></div>,
 <div class="hoverinfo" id="info3572" rel="m3572"></div>,
 <div class="hoverinfo" id="info98380" rel="m98380"></div>,
 <div class="hoverinfo" id="info138406" rel="m138406"></div>,
 <div class="hoverinfo" id="info48399" rel="m48399"></div>,
 <div class="hoverinfo" id="info87397" rel="m87397"></div>,
 <div class="hoverinfo" id="info77597" rel="m77597"></div>,
 <div class="hoverinfo" id="info88930" rel="m88930"></div>,
 <div class="hoverinfo" id="info110771" rel="m110771"></div>,
 <div class="hoverinfo" id="info121213" rel="m121213"></div>,
 <div class="hoverinfo" id="info658" rel="m658"></div>,
 <div class="hoverinfo" id="info3866" rel="m3866"></div>,
 <div class="hoverinfo" id="info42451" rel="m42451"></div>,
 <div class="hoverinfo" id="info138673" rel="m138673"></div>,
 <div class="hoverinfo" id="info93699" rel="m93699"></div>,
 <div class="hoverinfo" id="info94376" rel="m94376"></div>,
 <div class="hoverinfo" id="info419" rel="m419"></div>,
 <div class="hoverinfo" id="info974" rel="m974"></div>,
 <div class="hoverinfo" id="info3573" rel="m3573"></div>,
 <div class="hoverinfo" id="info8967" rel="m8967"></div>,
 <div class="hoverinfo" id="info8586" rel="m8586"></div>,
 <div class="hoverinfo" id="info99314" rel="m99314"></div>,
 <div class="hoverinfo" id="info162964" rel="m162964"></div>,
 <div class="hoverinfo" id="info110160" rel="m110160"></div>,
 <div class="hoverinfo" id="info62795" rel="m62795"></div>,
 <div class="hoverinfo" id="info87953" rel="m87953"></div>,
 <div class="hoverinfo" id="info768" rel="m768"></div>,
 <div class="hoverinfo" id="info2921" rel="m2921"></div>,
 <div class="hoverinfo" id="info3082" rel="m3082"></div>,
 <div class="hoverinfo" id="info6164" rel="m6164"></div>,
 <div class="hoverinfo" id="info12854" rel="m12854"></div>,
 <div class="hoverinfo" id="info26728" rel="m26728"></div>,
 <div class="hoverinfo" id="info33031" rel="m33031"></div>,
 <div class="hoverinfo" id="info48621" rel="m48621"></div>,
 <div class="hoverinfo" id="info166372" rel="m166372"></div>,
 <div class="hoverinfo" id="info93516" rel="m93516"></div>,
 <div class="hoverinfo" id="info149493" rel="m149493"></div>,
 <div class="hoverinfo" id="info22651" rel="m22651"></div>,
 <div class="hoverinfo" id="info87609" rel="m87609"></div>,
 <div class="hoverinfo" id="info10" rel="m10"></div>,
 <div class="hoverinfo" id="info85" rel="m85"></div>,
 <div class="hoverinfo" id="info106" rel="m106"></div>,
 <div class="hoverinfo" id="info401" rel="m401"></div>,
 <div class="hoverinfo" id="info1414" rel="m1414"></div>,
 <div class="hoverinfo" id="info9711" rel="m9711"></div>,
 <div class="hoverinfo" id="info660" rel="m660"></div>,
 <div class="hoverinfo" id="info16081" rel="m16081"></div>,
 <div class="hoverinfo" id="info95012" rel="m95012"></div>,
 <div class="hoverinfo" id="info115730" rel="m115730"></div>,
 <div class="hoverinfo" id="info118804" rel="m118804"></div>,
 <div class="hoverinfo" id="info122663" rel="m122663"></div>,
 <div class="hoverinfo" id="info144011" rel="m144011"></div>,
 <div class="hoverinfo" id="info24692" rel="m24692"></div>,
 <div class="hoverinfo" id="info39325" rel="m39325"></div>,
 <div class="hoverinfo" id="info48347" rel="m48347"></div>,
 <div class="hoverinfo" id="info89087" rel="m89087"></div>,
 <div class="hoverinfo" id="info106602" rel="m106602"></div>,
 <div class="hoverinfo" id="info869" rel="m869"></div>,
 <div class="hoverinfo" id="info936" rel="m936"></div>,
 <div class="hoverinfo" id="info3281" rel="m3281"></div>,
 <div class="hoverinfo" id="info138424" rel="m138424"></div>,
 <div class="hoverinfo" id="info83903" rel="m83903"></div>,
 <div class="hoverinfo" id="info121781" rel="m121781"></div>,
 <div class="hoverinfo" id="info122906" rel="m122906"></div>,
 <div class="hoverinfo" id="info133431" rel="m133431"></div>,
 <div class="hoverinfo" id="info136103" rel="m136103"></div>,
 <div class="hoverinfo" id="info118737" rel="m118737"></div>,
 <div class="hoverinfo" id="info104241" rel="m104241"></div>,
 <div class="hoverinfo" id="info25096" rel="m25096"></div>,
 <div class="hoverinfo" id="info49835" rel="m49835"></div>,
 <div class="hoverinfo" id="info923" rel="m923"></div>,
 <div class="hoverinfo" id="info3571" rel="m3571"></div>,
 <div class="hoverinfo" id="info154545" rel="m154545"></div>,
 <div class="hoverinfo" id="info90531" rel="m90531"></div>,
 <div class="hoverinfo" id="info113819" rel="m113819"></div>,
 <div class="hoverinfo" id="info2895" rel="m2895"></div>,
 <div class="hoverinfo" id="info61189" rel="m61189"></div>,
 <div class="hoverinfo" id="info58141" rel="m58141"></div>,
 <div class="hoverinfo" id="info62023" rel="m62023"></div>,
 <div class="hoverinfo" id="info93972" rel="m93972"></div>,
 <div class="hoverinfo" id="info98436" rel="m98436"></div>,
 <div class="hoverinfo" id="info139629" rel="m139629"></div>,
 <div class="hoverinfo" id="info142310" rel="m142310"></div>,
 <div class="hoverinfo" id="info147692" rel="m147692"></div>,
 <div class="hoverinfo" id="info31" rel="m31"></div>,
 <div class="hoverinfo" id="info320" rel="m320"></div>,
 <div class="hoverinfo" id="info895" rel="m895"></div>,
 <div class="hoverinfo" id="info16816" rel="m16816"></div>,
 <div class="hoverinfo" id="info131338" rel="m131338"></div>,
 <div class="hoverinfo" id="info119282" rel="m119282"></div>,
 <div class="hoverinfo" id="info123444" rel="m123444"></div>,
 <div class="hoverinfo" id="info95243" rel="m95243"></div>,
 <div class="hoverinfo" id="info100922" rel="m100922"></div>,
 <div class="hoverinfo" id="info443" rel="m443"></div>,
 <div class="hoverinfo" id="info736" rel="m736"></div>,
 <div class="hoverinfo" id="info1013" rel="m1013"></div>,
 <div class="hoverinfo" id="info1600" rel="m1600"></div>,
 <div class="hoverinfo" id="info3575" rel="m3575"></div>,
 <div class="hoverinfo" id="info10552" rel="m10552"></div>,
 <div class="hoverinfo" id="info147585" rel="m147585"></div>,
 <div class="hoverinfo" id="info37755" rel="m37755"></div>,
 <div class="hoverinfo" id="info40761" rel="m40761"></div>,
 <div class="hoverinfo" id="info118568" rel="m118568"></div>,
 <div class="hoverinfo" id="info57791" rel="m57791"></div>,
 <div class="hoverinfo" id="info77609" rel="m77609"></div>,
 <div class="hoverinfo" id="info81117" rel="m81117"></div>,
 <div class="hoverinfo" id="info3378" rel="m3378"></div>,
 <div class="hoverinfo" id="info7458" rel="m7458"></div>,
 <div class="hoverinfo" id="info9699" rel="m9699"></div>,
 <div class="hoverinfo" id="info12471" rel="m12471"></div>,
 <div class="hoverinfo" id="info15306" rel="m15306"></div>,
 <div class="hoverinfo" id="info9" rel="m9"></div>,
 <div class="hoverinfo" id="info18" rel="m18"></div>,
 <div class="hoverinfo" id="info29" rel="m29"></div>,
 <div class="hoverinfo" id="info149" rel="m149"></div>,
 <div class="hoverinfo" id="info735" rel="m735"></div>,
 <div class="hoverinfo" id="info14236" rel="m14236"></div>,
 <div class="hoverinfo" id="info16144" rel="m16144"></div>,
 <div class="hoverinfo" id="info16922" rel="m16922"></div>,
 <div class="hoverinfo" id="info112774" rel="m112774"></div>,
 <div class="hoverinfo" id="info26704" rel="m26704"></div>,
 <div class="hoverinfo" id="info84983" rel="m84983"></div>,
 <div class="hoverinfo" id="info24" rel="m24"></div>,
 <div class="hoverinfo" id="info79" rel="m79"></div>,
 <div class="hoverinfo" id="info267" rel="m267"></div>,
 <div class="hoverinfo" id="info583" rel="m583"></div>,
 <div class="hoverinfo" id="info762" rel="m762"></div>,
 <div class="hoverinfo" id="info838" rel="m838"></div>,
 <div class="hoverinfo" id="info1061" rel="m1061"></div>,
 <div class="hoverinfo" id="info1111" rel="m1111"></div>,
 <div class="hoverinfo" id="info1262" rel="m1262"></div>,
 <div class="hoverinfo" id="info1263" rel="m1263"></div>,
 <div class="hoverinfo" id="info2459" rel="m2459"></div>,
 <div class="hoverinfo" id="info6520" rel="m6520"></div>,

In [51]:
import regex as re
def mofo(text):
    numbers = re.findall(r'\d+', text)
    return numbers

In [200]:
dummy_list=[]
for i in list_:
    dummy_list.append(int(mofo(str(i))[0]))

In [196]:
for i in [50,100,150,200,250,300,350,400,450,500,550,600]:
    url1 = f"https://myanimelist.net/topmanga.php?limit={i}"
    page=requests.get(url1)
    soup=BeautifulSoup(page.text)
    for i in soup.find_all("div",class_="hoverinfo"):
        list_.append(i)

In [148]:
dummy_list=[]
url1 = f"https://myanimelist.net/topmanga.php?limit=100"
page=requests.get(url)
soup=BeautifulSoup(page.text)
list_=[]
for j in list_:
        dummy_list.append(int(mofo(str(j))[0]))

In [202]:
dummy_list

[2,
 1706,
 656,
 13,
 1,
 51,
 642,
 25,
 130826,
 162032,
 70345,
 143441,
 16765,
 4632,
 44489,
 657,
 3,
 1303,
 104,
 14893,
 121405,
 23751,
 34053,
 90125,
 126479,
 336,
 1224,
 35243,
 140765,
 56805,
 44227,
 104039,
 126287,
 21525,
 70261,
 9115,
 28,
 651,
 7375,
 74697,
 144267,
 147272,
 89357,
 123992,
 86119,
 100448,
 85781,
 86769,
 26,
 14483,
 7,
 102875,
 40171,
 91941,
 132678,
 44347,
 72467,
 147769,
 45143,
 116778,
 125036,
 418,
 21,
 145,
 55215,
 1133,
 1859,
 664,
 121496,
 100035,
 4,
 9726,
 117077,
 123006,
 129621,
 88660,
 98930,
 107562,
 145863,
 23900,
 26027,
 24875,
 78523,
 85968,
 103237,
 128365,
 137200,
 44,
 904,
 6978,
 81,
 745,
 81669,
 60783,
 70399,
 35513,
 132214,
 102256,
 107931,
 60553,
 756,
 9982,
 118289,
 114043,
 116312,
 145539,
 37707,
 61579,
 399,
 698,
 3006,
 13245,
 3031,
 11514,
 92559,
 87844,
 147448,
 138533,
 610,
 1325,
 2062,
 11054,
 134744,
 23390,
 66517,
 105084,
 164926,
 22,
 8157,
 11327,
 102,
 3083,
 5744,
 147171,
 159387,
 137303,
 101396,
 108177,
 79993,
 33327,
 39859,
 81211,
 214,
 1342,
 21498,
 44307,
 79085,
 146878,
 30,
 3649,
 11734,
 93097,
 92299,
 104538,
 56529,
 85719,
 113010,
 115506,
 119161,
 121504,
 28393,
 141120,
 111213,
 114745,
 87610,
 38071,
 25515,
 46282,
 117851,
 119072,
 121269,
 123649,
 93753,
 88639,
 1183,
 43,
 7519,
 112988,
 135496,
 36413,
 97244,
 100323,
 115922,
 3299,
 4658,
 7482,
 143325,
 42001,
 21499,
 42,
 1032,
 1469,
 3285,
 6812,
 112370,
 119279,
 124374,
 155861,
 743,
 3807,
 17051,
 29211,
 119184,
 133641,
 3572,
 98380,
 138406,
 48399,
 87397,
 77597,
 88930,
 110771,
 121213,
 658,
 3866,
 42451,
 138673,
 93699,
 94376,
 419,
 974,
 3573,
 8967,
 8586,
 99314,
 162964,
 110160,
 62795,
 87953,
 768,
 2921,
 3082,
 6164,
 12854,
 26728,
 33031,
 48621,
 166372,
 93516,
 149493,
 22651,
 87609,
 10,
 85,
 106,
 401,
 1414,
 9711,
 660,
 16081,
 95012,
 115730,
 118804,
 122663,
 144011,
 24692,
 39325,
 48347,
 89087,
 106602,
 869,
 936,
 3281,
 138424,
 83903,
 121781,
 122906,
 133431,
 136103,
 118737,
 104241,
 25096,
 49835,
 923,
 3571,
 154545,
 90531,
 113819,
 2895,
 61189,
 58141,
 62023,
 93972,
 98436,
 139629,
 142310,
 147692,
 31,
 320,
 895,
 16816,
 131338,
 119282,
 123444,
 95243,
 100922,
 443,
 736,
 1013,
 1600,
 3575,
 10552,
 147585,
 37755,
 40761,
 118568,
 57791,
 77609,
 81117,
 3378,
 7458,
 9699,
 12471,
 15306,
 9,
 18,
 29,
 149,
 735,
 14236,
 16144,
 16922,
 112774,
 26704,
 84983,
 24,
 79,
 267,
 583,
 762,
 838,
 1061,
 1111,
 1262,
 1263,
 2459,
 6520,
 9548,
 30079,
 35573,
 102343,
 106809,
 138481,
 146909,
 148137,
 148542,
 156681,
 124845,
 57,
 704,
 1047,
 18161,
 47022,
 17910,
 165876,
 72025,
 5255,
 14790,
 98379,
 113138,
 119392,
 135545,
 112807,
 119022,
 120616,
 145496,
 17904,
 23571,
 39883,
 43921,
 44711,
 91514,
 1009,
 1097,
 1649,
 4258,
 7776,
 375,
 481,
 3009,
 154587,
 112091,
 92252,
 96044,
 43915,
 24308,
 47825,
 128,
 445,
 915,
 4571,
 4625,
 10884,
 11593,
 103701,
 103989,
 56743,
 56755,
 112115,
 113555,
 132877,
 110031,
 112318,
 26144,
 141833,
 146798,
 62547,
 158,
 1315,
 1461,
 1802,
 14531,
 16593,
 348,
 585,
 731,
 1075,
 1208,
 1320,
 3731,
 5651,
 17552,
 131008,
 132962,
 133352,
 134997,
 58027,
 103063,
 106204,
 107548,
 108495,
 108566,
 102330,
 18074,
 24705,
 26736,
 37523,
 510,
 7149,
 15805,
 70801,
 147062,
 148234,
 162733,
 131799,
 111211,
 118646,
 126146,
 103897,
 140409,
 151061,
 92,
 373,
 2924,
 58563,
 55869,
 115746,
 124470,
 174045,
 27231,
 45855,
 46010,
 53,
 1014,
 1218,
 1982,
 3008,
 4453,
 9738,
 104491,
 107875,
 112694,
 115122,
 121480,
 130832,
 131334,
 134341,
 3715,
 25409,
 30315,
 140295,
 141043,
 147863,
 162158,
 163877,
 58007,
 67401,
 80375,
 35171,
 41865,
 43913,
 45947,
 112589,
 113163,
 125052,
 436,
 929,
 994,
 10865,
 661,
 705,
 3042,
 8144,
 8652,
 96573,
 102703,
 111229,
 114787,
 117840,
 118625,
 77637,
 80091,
 84255,
 34127,
 35733,
 20242,
 21467,
 33297,
 36131,
 44319,
 45885,
 17,
 688,
 729,
 770,
 1110,
 1297,
 1630,
 1695,
 8070,
 8557,
 10443,
 11850,
 96792,
 100128,
 127332,
 120250,
 120875,
 20554,
 21784,
 26769,
 149090,
 63535,
 792,
 9546,
 10978,
 463,
 635,
 1076,
 7010,
 7760,
 10010,
 10892,
 24294,
 111745,
 127221,
 80841,
 85773,
 99969,
 107948,
 147454,
 152024,
 153158,
 21054,
 36933,
 20,
 338,
 1033,
 1101,
 1365,
 3403,
 4423,
 4945,
 8300,
 89960,
 112090,
 112922,
 70259,
 27029,
 29983,
 48025,
 154679,
 166865,
 170427,
 113671,
 123435,
 47,
 339,
 1258,
 9296,
 11243,
 11652,
 13702,
 27,
 564,
 674,
 872,
 908,
 928,
 1149,
 1257,
 7749,
 10447,
 148467,
 62671,
 78537,
 80281,
 19709,
 26201,
 41435,
 112245,
 117020,
 124094,
 130331,
 132505,
 168980,
 89768,
 107417,
 108187,
 108696,
 76965,
 393,
 591,
 988,
 3097,
 3574,
 137939,
 148245,
 159130,
 26178,
 44523,
 119931,
 121303,
 114793,
 115710,
 120318,
 128594,
 134612,
 11,
 633,
 655,
 3102,
 89467,
 90810,
 95211,
 95964,
 24457,
 138407,
 139104,
 142799]

In [366]:
dummy_list[411:441]

[14531,
 16593,
 348,
 585,
 731,
 1075,
 1208,
 1320,
 3731,
 5651,
 17552,
 131008,
 132962,
 133352,
 134997,
 58027,
 103063,
 106204,
 107548,
 108495,
 108566,
 102330,
 18074,
 24705,
 26736,
 37523,
 510,
 7149,
 15805,
 70801]

In [429]:
genre=[]
for i in dummy_list[621:651]:
    url = f"https://myanimelist.net/manga/{i}"
    page=requests.get(url)
    soup=BeautifulSoup(page.text)
    a=[]
    for j in soup.find_all("span",itemprop="genre"):
        a.append(j.text)
    genre.append(a)

In [431]:
genre

[['Award Winning', 'Drama', 'Mystery', 'Supernatural', 'Detective', 'Shounen'],
 ['Comedy', 'Romance', 'School', 'Shoujo'],
 ['Action', 'Comedy', 'Drama', 'Ecchi', 'Martial Arts', 'Shounen'],
 ['Drama', 'Fantasy', 'Sci-Fi', 'Slice of Life', 'Supernatural', 'Seinen'],
 ['Drama', 'Adult Cast', 'Psychological', 'Strategy Game', 'Seinen'],
 ['Award Winning', 'Drama', 'Historical', 'Seinen'],
 ['Boys Love', 'Comedy', 'Adult Cast', 'Organized Crime'],
 ['Comedy', 'Gag Humor', 'Seinen'],
 ['Action', 'Supernatural', 'Historical', 'Shoujo'],
 ['Fantasy'],
 ['Boys Love', 'Drama', 'Supernatural'],
 ['Boys Love', 'Comedy', 'Supernatural', 'Adult Cast', 'Workplace'],
 ['Adventure', 'Fantasy', 'Slice of Life', 'Psychological'],
 ['Action', 'Supernatural', 'Shounen'],
 ['Drama', 'Fantasy', 'Romance'],
 ['Action', 'Adventure', 'Fantasy', 'Super Power', 'Shounen'],
 ['Drama', 'Romance', 'Supernatural'],
 ['Action', 'Adventure', 'Fantasy', 'Martial Arts', 'Shounen'],
 ['Comedy', 'Romance', 'School', 'Shoujo'],
 ['Drama',
  'Fantasy',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Reincarnation',
  'Space',
  'Shoujo'],
 ['Girls Love', 'School', 'Seinen'],
 ['Comedy', 'Slice of Life', 'School', 'Shounen'],
 ['Fantasy', 'Mahou Shoujo'],
 ['Drama', 'Romance', 'Sci-Fi', 'Love Polygon', 'School', 'Time Travel'],
 ['Action', 'Fantasy', 'Super Power', 'Urban Fantasy', 'Vampire', 'Shounen'],
 ['Drama', 'Fantasy', 'Horror', 'Mahou Shoujo', 'School'],
 ['Drama', 'Mystery', 'Sci-Fi'],
 ['Romance', 'Shoujo'],
 ['Comedy', 'Romance', 'Adult Cast', 'Crossdressing']]

In [102]:
import pandas as pd
df=pd.read_csv(r'C:\Users\dtrri\bot\temp2.csv')

In [110]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [433]:
df['Genre'][621:651]=genre

C:\Users\dtrri\AppData\Local\Temp\ipykernel_26516\2486546725.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Genre'][621:651]=genre

In [435]:
df

,Rank,name,rating,Format,Volume Count,Start Date,End Date,Member Count,Genre
0,1,Berserk,9.47,Manga,unfinished,Aug 1989,unfinished,740803,"[Action, Adventure, Award Winning, Drama, Fant..."
1,2,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga,24 vols,Jan 2004,Apr 2011,287531,"[Action, Adventure, Mystery, Supernatural, His..."
2,3,Vagabond,9.26,Manga,37 vols,Sep 1998,May 2015,417041,"[Action, Adventure, Award Winning, Historical,..."
3,4,One Piece,9.22,Manga,unfinished,Jul 1997,unfinished,653920,"[Action, Adventure, Fantasy, Shounen]"
4,5,Monster,9.16,Manga,18 vols,Dec 1994,Dec 2001,264525,"[Award Winning, Drama, Mystery, Adult Cast, Ps..."
...,...,...,...,...,...,...,...,...,...
645,646,Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu ...,8.77,Light Novel,15 vols,Jan 2020,Nov 2024,39292,"[Action, Fantasy, Super Power, Urban Fantasy, ..."
646,647,"Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, ...",8.77,Manga,3 vols,Aug 2016,Oct 2017,175768,"[Drama, Fantasy, Horror, Mahou Shoujo, School]"
647,648,Dungeon Meshi,8.76,Manga,14 vols,Feb 2014,Sep 2023,93656,"[Drama, Mystery, Sci-Fi]"
648,649,Hunter x Hunter,8.76,Manga,unfinished,Mar 1998,unfinished,290839,"[Romance, Shoujo]"
649,650,Uchuu Kyoudai,8.75,Manga,unfinished,Dec 2007,unfinished,37464,"[Comedy, Romance, Adult Cast, Crossdressing]"

In [437]:
df["Genre"].value_counts()

Genre
[Drama]                                                        5
[Award Winning, Sports, School, Team Sports, Shounen]          5
[Comedy, Romance, School, Shoujo]                              5
[Drama, Horror, Mystery, Psychological]                        4
[Action, Adventure, Fantasy, Shounen]                          4
                                                              ..
[Drama, Josei]                                                 1
[Fantasy, Mystery, Seinen]                                     1
[Action, Adventure, Comedy, Fantasy, Isekai, Reincarnation]    1
[Drama, Romance, Historical, Military, Shoujo]                 1
[Comedy, Romance, Adult Cast, Crossdressing]                   1
Name: count, Length: 546, dtype: int64

In [439]:
df.to_csv(r'C:\Users\dtrri\bot\EDA_PROJECT.csv')

In [33]:
df1=pd.read_csv(r'C:\Users\dtrri\bot\EDA_PROJECT.csv')

In [35]:
df1

,Unnamed: 0,Rank,name,rating,Format,Volume Count,Start Date,End Date,Member Count,Genre
0,0,1,Berserk,9.47,Manga,unfinished,Aug 1989,unfinished,740803,"['Action', 'Adventure', 'Award Winning', 'Dram..."
1,1,2,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga,24 vols,Jan 2004,Apr 2011,287531,"['Action', 'Adventure', 'Mystery', 'Supernatur..."
2,2,3,Vagabond,9.26,Manga,37 vols,Sep 1998,May 2015,417041,"['Action', 'Adventure', 'Award Winning', 'Hist..."
3,3,4,One Piece,9.22,Manga,unfinished,Jul 1997,unfinished,653920,"['Action', 'Adventure', 'Fantasy', 'Shounen']"
4,4,5,Monster,9.16,Manga,18 vols,Dec 1994,Dec 2001,264525,"['Award Winning', 'Drama', 'Mystery', 'Adult C..."
...,...,...,...,...,...,...,...,...,...,...
645,645,646,Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu ...,8.77,Light Novel,15 vols,Jan 2020,Nov 2024,39292,"['Action', 'Fantasy', 'Super Power', 'Urban Fa..."
646,646,647,"Jumyou wo Kaitotte Moratta. Ichinen ni Tsuki, ...",8.77,Manga,3 vols,Aug 2016,Oct 2017,175768,"['Drama', 'Fantasy', 'Horror', 'Mahou Shoujo',..."
647,647,648,Dungeon Meshi,8.76,Manga,14 vols,Feb 2014,Sep 2023,93656,"['Drama', 'Mystery', 'Sci-Fi']"
648,648,649,Hunter x Hunter,8.76,Manga,unfinished,Mar 1998,unfinished,290839,"['Romance', 'Shoujo']"
649,649,650,Uchuu Kyoudai,8.75,Manga,unfinished,Dec 2007,unfinished,37464,"['Comedy', 'Romance', 'Adult Cast', 'Crossdres..."

In [ ]:
"rank":rank,
                 'name':name,
                "details":details,
                "rating":rating

In [71]:
df1.columns

Index(['Unnamed: 0', 'Rank', 'name', 'rating', 'Format', 'Volume Count',
       'Start Date', 'End Date', 'Member Count', 'Genre'],
      dtype='object')

In [73]:
df_cleaned.columns

Index(['name', 'rating', 'Format', 'Volume Count', 'Start Date', 'End Date',
       'Member Count'],
      dtype='object')

In [65]:
df1['name']=df_cleaned['name']

In [67]:
df1['rating']=df_cleaned['rating']

In [75]:
df1['Format']=df_cleaned['Format']

In [77]:
df1['Volume Count']=df_cleaned['Volume Count']

In [79]:
df1['Start Date']=df_cleaned['Start Date']

In [83]:
df1['End Date']=df_cleaned['End Date']

In [81]:
df1['Member Count']=df_cleaned['Member Count']

In [85]:
df1

,Unnamed: 0,Rank,name,rating,Format,Volume Count,Start Date,End Date,Member Count,Genre
0,0,1,Berserk,9.47,Manga,unfinished,Aug 1989,unfinished,741230,"['Action', 'Adventure', 'Award Winning', 'Dram..."
1,1,2,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga,24 vols,Jan 2004,Apr 2011,287722,"['Action', 'Adventure', 'Mystery', 'Supernatur..."
2,2,3,Vagabond,9.26,Manga,37 vols,Sep 1998,May 2015,417353,"['Action', 'Adventure', 'Award Winning', 'Hist..."
3,3,4,One Piece,9.22,Manga,unfinished,Jul 1997,unfinished,654245,"['Action', 'Adventure', 'Fantasy', 'Shounen']"
4,4,5,Monster,9.16,Manga,18 vols,Dec 1994,Dec 2001,264699,"['Award Winning', 'Drama', 'Mystery', 'Adult C..."
...,...,...,...,...,...,...,...,...,...,...
645,645,646,Goukon ni Ittara Onna ga Inakatta Hanashi,8.07,Manga,unfinished,Feb 2021,unfinished,5576,"['Action', 'Fantasy', 'Super Power', 'Urban Fa..."
646,646,647,Hitoribocchi no ○○ Seikatsu,8.07,Manga,8 vols,Sep 2013,Apr 2021,25442,"['Drama', 'Fantasy', 'Horror', 'Mahou Shoujo',..."
647,647,648,Nogi Wakaba wa Yuusha de Aru,8.07,Light Novel,2 vols,Jul 2015,Jan 2017,4899,"['Drama', 'Mystery', 'Sci-Fi']"
648,648,649,Orange,8.07,Light Novel,3 vols,Jul 2015,Mar 2016,9831,"['Romance', 'Shoujo']"
649,649,650,Mahou Shoujo Madoka★Magica,8.07,Manga,3 vols,Feb 2011,May 2011,41688,"['Comedy', 'Romance', 'Adult Cast', 'Crossdres..."

In [87]:
top_5_rated = df1[['name', 'rating']].sort_values(by='rating', ascending=False).head(35)
top_5_rated

                                                 name rating
0                                             Berserk   9.47
1     JoJo no Kimyou na Bouken Part 7: Steel Ball Run   9.32
2                                            Vagabond   9.26
3                                           One Piece   9.22
4                                             Monster   9.16
5                                           Slam Dunk   9.08
6                                        Vinland Saga   9.08
7                                 Fullmetal Alchemist   9.04
10                                         Grand Blue   9.03
8                                      Tian Guan Cifu   9.03
9                                       Guimi Zhi Zhu   9.03
11                      Omniscient Reader's Viewpoint   9.02
12                                            Kingdom   9.01
13                                     Oyasumi Punpun   8.99
14                                    Houseki no Kuni   8.97
15                                               Real   8.95
16                                  20th Century Boys   8.94
17                                      Ashita no Joe   8.94
19                    Monogatari Series: First Season   8.91
20                                      Mo Dao Zu Shi   8.91
18                                        Yotsuba to!   8.91
22  Umineko no Naku Koro ni Chiru - Episode 8: Twi...   8.90
21                   Monogatari Series: Second Season   8.90
23  Kaguya-sama wa Kokurasetai: Tensai-tachi no Re...   8.89
24                                Mikkakan no Koufuku   8.87
25                                                GTO   8.87
26                                    3-gatsu no Lion   8.86
27                                          Haikyuu!!   8.86
28                                     Tian Guan Cifu   8.85
29                                     Koe no Katachi   8.85
32                                  Sousou no Frieren   8.83
30                    Monogatari Series: Final Season   8.83
31                                                 86   8.83
33                                   Akatsuki no Yona   8.82
34           Mushoku Tensei: Isekai Ittara Honki Dasu   8.82

In [89]:
unique_titles_count = df1['name'].nunique()
unique_titles_count

629

In [91]:
df1['name'].value_counts()

name
Orange                                                 2
Mo Dao Zu Shi                                          2
Bungou Stray Dogs: Dazai, Chuuya, Juugosai             2
Kimi no Suizou wo Tabetai                              2
Roxana                                                 2
                                                      ..
Tomodachi Game                                         1
Shousetsu Akatsuki no Yona: Onaji Tsuki no Shita de    1
Gunnm                                                  1
Kaichou wa Maid-sama!                                  1
Mahou Shoujo Madoka★Magica                             1
Name: count, Length: 629, dtype: int64

In [115]:
df1[['name', 'rating', 'Format', 'Volume Count', 'Start Date', 'End Date','Member Count']].duplicated().sum()

2

In [109]:
df_cleaned.duplicated().sum()

2

In [103]:
df_cleaned[df_cleaned.duplicated()]

,name,rating,Format,Volume Count,Start Date,End Date,Member Count
560,Roxana,8.12,Manhwa,unfinished,Jan 2021,unfinished,13058
561,"Bungou Stray Dogs: Dazai, Chuuya, Juugosai",8.12,Manga,4 vols,Sep 2022,Aug 2024,2138

In [105]:
df_cleaned.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
645    False
646    False
647    False
648    False
649    False
Length: 650, dtype: bool

In [117]:
df1

,Unnamed: 0,Rank,name,rating,Format,Volume Count,Start Date,End Date,Member Count,Genre
0,0,1,Berserk,9.47,Manga,unfinished,Aug 1989,unfinished,741230,"['Action', 'Adventure', 'Award Winning', 'Dram..."
1,1,2,JoJo no Kimyou na Bouken Part 7: Steel Ball Run,9.32,Manga,24 vols,Jan 2004,Apr 2011,287722,"['Action', 'Adventure', 'Mystery', 'Supernatur..."
2,2,3,Vagabond,9.26,Manga,37 vols,Sep 1998,May 2015,417353,"['Action', 'Adventure', 'Award Winning', 'Hist..."
3,3,4,One Piece,9.22,Manga,unfinished,Jul 1997,unfinished,654245,"['Action', 'Adventure', 'Fantasy', 'Shounen']"
4,4,5,Monster,9.16,Manga,18 vols,Dec 1994,Dec 2001,264699,"['Award Winning', 'Drama', 'Mystery', 'Adult C..."
...,...,...,...,...,...,...,...,...,...,...
645,645,646,Goukon ni Ittara Onna ga Inakatta Hanashi,8.07,Manga,unfinished,Feb 2021,unfinished,5576,"['Action', 'Fantasy', 'Super Power', 'Urban Fa..."
646,646,647,Hitoribocchi no ○○ Seikatsu,8.07,Manga,8 vols,Sep 2013,Apr 2021,25442,"['Drama', 'Fantasy', 'Horror', 'Mahou Shoujo',..."
647,647,648,Nogi Wakaba wa Yuusha de Aru,8.07,Light Novel,2 vols,Jul 2015,Jan 2017,4899,"['Drama', 'Mystery', 'Sci-Fi']"
648,648,649,Orange,8.07,Light Novel,3 vols,Jul 2015,Mar 2016,9831,"['Romance', 'Shoujo']"
649,649,650,Mahou Shoujo Madoka★Magica,8.07,Manga,3 vols,Feb 2011,May 2011,41688,"['Comedy', 'Romance', 'Adult Cast', 'Crossdres..."

In [119]:
df1.to_csv(r'C:\Users\dtrri\bot\EDA_PROJECT_v2.csv',index=False)