In [10]:
import numpy as np
from itertools import product
a=(list(product(*[[1,2,3,4,5,6],[1,2,3,4,5,6]])))
a

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)]

In [30]:
from itertools import product
a = list(product([1, 2, 3, 4, 5, 6], repeat=2))
b=[[] for _ in range(6)]
for i in range(6):
    for j in range(6):
        b[i].append(a[(i*6)+j])
        
print(b)

[[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6)], [(2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6)], [(3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6)], [(4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6)], [(5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6)], [(6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)]]

In [23]:
from itertools import product

# Generate all possible pairs of dice rolls
a = list(product([1, 2, 3, 4, 5, 6], repeat=2))

# Create an empty list b with 6 sublists
b = [[] for _ in range(6)]

# Fill the sublists in b with the appropriate pairs from a
for i in range(6):
    for j in range(6):
        b[i].append(a[(i * 6) + j])

# Print the result
print(b)

[[(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6)], [(2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6)], [(3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6)], [(4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6)], [(5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6)], [(6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6)]]

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"D:\Downloads\weather_forecast.csv")

In [3]:
df

     Outlook Temperature Humidity   Windy Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No

In [8]:
df.groupby(['Temperature','Play'])["Play"].count()

Temperature  Play
Cool         No      1
             Yes     3
Hot          No      2
             Yes     2
Mild         No      2
             Yes     4
Name: Play, dtype: int64

In [4]:
pd.crosstab(df['Temperature'],df['Play'])

Play         No  Yes
Temperature
Cool          1    3
Hot           2    2
Mild          2    4

In [6]:
(pd.crosstab(df['Temperature'],df['Play'])/len(df))*100

Play                No        Yes
Temperature
Cool          7.142857  21.428571
Hot          14.285714  14.285714
Mild         14.285714  28.571429

In [7]:
(pd.crosstab(df['Temperature'],df['Play'],margins=True)/len(df))*100

Play                No        Yes         All
Temperature
Cool          7.142857  21.428571   28.571429
Hot          14.285714  14.285714   28.571429
Mild         14.285714  28.571429   42.857143
All          35.714286  64.285714  100.000000

In [11]:
pd.crosstab(df['Temperature'],df['Play'],normalize = "index",margins=True)

Play               No       Yes
Temperature
Cool         0.250000  0.750000
Hot          0.500000  0.500000
Mild         0.333333  0.666667
All          0.357143  0.642857

In [14]:
pd.crosstab(df['Outlook'],df['Play'],margins=True)/len(df)

Play            No       Yes       All
Outlook
Overcast  0.000000  0.285714  0.285714
Rain      0.142857  0.214286  0.357143
Sunny     0.214286  0.142857  0.357143
All       0.357143  0.642857  1.000000

In [19]:
pd.crosstab(df['Outlook'],df['Play'],normalize="index")

Play       No  Yes
Outlook
Overcast  0.0  1.0
Rain      0.4  0.6
Sunny     0.6  0.4

In [20]:
pd.crosstab(df['Outlook'],df['Play'],normalize="columns")

Play       No       Yes
Outlook
Overcast  0.0  0.444444
Rain      0.4  0.333333
Sunny     0.6  0.222222